# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lookups_pb2 as lookups__pb2


class LookupsServiceStub(object):
    """The Lookups service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLookups = channel.unary_unary(
                '/lookupsservice.LookupsService/GetLookups',
                request_serializer=lookups__pb2.LookupRequest.SerializeToString,
                response_deserializer=lookups__pb2.LookupResponse.FromString,
                )


class LookupsServiceServicer(object):
    """The Lookups service definition.
    """

    def GetLookups(self, request, context):
        """A method for performing a lookup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LookupsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLookups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLookups,
                    request_deserializer=lookups__pb2.LookupRequest.FromString,
                    response_serializer=lookups__pb2.LookupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lookupsservice.LookupsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LookupsService(object):
    """The Lookups service definition.
    """

    @staticmethod
    def GetLookups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lookupsservice.LookupsService/GetLookups',
            lookups__pb2.LookupRequest.SerializeToString,
            lookups__pb2.LookupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
