# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lookups.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlookups.proto\x12\x0elookupsservice\"\x1e\n\rLookupRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\x0eLookupResponse\x12\x0f\n\x07results\x18\x01 \x03(\t2]\n\x0eLookupsService\x12K\n\nGetLookups\x12\x1d.lookupsservice.LookupRequest\x1a\x1e.lookupsservice.LookupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lookups_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOOKUPREQUEST']._serialized_start=33
  _globals['_LOOKUPREQUEST']._serialized_end=63
  _globals['_LOOKUPRESPONSE']._serialized_start=65
  _globals['_LOOKUPRESPONSE']._serialized_end=98
  _globals['_LOOKUPSSERVICE']._serialized_start=100
  _globals['_LOOKUPSSERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
