# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import activity_log_pb2 as activity__log__pb2


class ActivityLogServiceStub(object):
    """The User service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMessage = channel.unary_unary(
                '/activitylogservice.ActivityLogService/CreateMessage',
                request_serializer=activity__log__pb2.CreateMessageRequest.SerializeToString,
                response_deserializer=activity__log__pb2.CreateMessageResponse.FromString,
                )


class ActivityLogServiceServicer(object):
    """The User service definition.
    """

    def CreateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivityLogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=activity__log__pb2.CreateMessageRequest.FromString,
                    response_serializer=activity__log__pb2.CreateMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'activitylogservice.ActivityLogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ActivityLogService(object):
    """The User service definition.
    """

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/activitylogservice.ActivityLogService/CreateMessage',
            activity__log__pb2.CreateMessageRequest.SerializeToString,
            activity__log__pb2.CreateMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
