# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x0buserservice\"`\n\x04User\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"m\n\x11\x43reateUserRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"A\n\x12\x43reateUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"F\n\x11UpdateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x1f\n\x04user\x18\x02 \x01(\x0b\x32\x11.userservice.User\"m\n\x12UpdateUserResponse\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"6\n\x10LoginUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"?\n\x11LoginUserResponse\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"&\n\x15GetCurrentUserRequest\x12\r\n\x05token\x18\x01 \x01(\t\"l\n\x16GetCurrentUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x10\n\x08username\x18\x05 \x01(\t2\xd2\x02\n\x0bUserService\x12M\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x1f.userservice.CreateUserResponse\x12M\n\nUpdateUser\x12\x1e.userservice.UpdateUserRequest\x1a\x1f.userservice.UpdateUserResponse\x12J\n\tLoginUser\x12\x1d.userservice.LoginUserRequest\x1a\x1e.userservice.LoginUserResponse\x12Y\n\x0eGetCurrentUser\x12\".userservice.GetCurrentUserRequest\x1a#.userservice.GetCurrentUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=28
  _globals['_USER']._serialized_end=124
  _globals['_CREATEUSERREQUEST']._serialized_start=126
  _globals['_CREATEUSERREQUEST']._serialized_end=235
  _globals['_CREATEUSERRESPONSE']._serialized_start=237
  _globals['_CREATEUSERRESPONSE']._serialized_end=302
  _globals['_UPDATEUSERREQUEST']._serialized_start=304
  _globals['_UPDATEUSERREQUEST']._serialized_end=374
  _globals['_UPDATEUSERRESPONSE']._serialized_start=376
  _globals['_UPDATEUSERRESPONSE']._serialized_end=485
  _globals['_LOGINUSERREQUEST']._serialized_start=487
  _globals['_LOGINUSERREQUEST']._serialized_end=541
  _globals['_LOGINUSERRESPONSE']._serialized_start=543
  _globals['_LOGINUSERRESPONSE']._serialized_end=606
  _globals['_GETCURRENTUSERREQUEST']._serialized_start=608
  _globals['_GETCURRENTUSERREQUEST']._serialized_end=646
  _globals['_GETCURRENTUSERRESPONSE']._serialized_start=648
  _globals['_GETCURRENTUSERRESPONSE']._serialized_end=756
  _globals['_USERSERVICE']._serialized_start=759
  _globals['_USERSERVICE']._serialized_end=1097
# @@protoc_insertion_point(module_scope)
